version: "3"
services:
  web:
    image: bugkiller448/kaufmann
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:3000"
    networks:
      - webnet
networks:
  webnet:
